services:
  iam:
    image: keycloak/keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeit
    ports:
      - 58443:8443
    volumes:
      - ./keycloak/conf/server.key:/opt/keycloak/conf/server.key
      - ./keycloak/conf/server.pem:/opt/keycloak/conf/server.pem
      - ./keycloak/conf/keycloak.ssl.conf:/opt/keycloak/conf/keycloak.conf
      - ~/data/keycloak/keycloak/data:/opt/keycloak/data
      - ~/data/keycloak/keycloak/log:/opt/keycloak/data/log
    networks:
      - iam
    command:
      - start
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M

networks:
  iam:
    driver: bridge
