services:
  db:
    image: trinodb/trino
    container_name: trino
    restart: always
    ports:
      - 58080:8080
    volumes:
      - ./conf/config.properties:/etc/trino/config.properties
      - ./conf/log.properties:/etc/trino/log.properties
      - ./conf/node.properties:/etc/trino/node.properties
      - ./catalog:/etc/trino/catalog
      - ~/data/trino/log:/data/trino/var/log
      - ~/data/trino/run:/data/trino/var/run
