services:

  hive-metastore:
    image: apache/hive:4.0.0
    hostname: hive-metastore
    container_name: hive-metastore
    restart: unless-stopped
    ports:
      - 59083:9083
    environment:
      - SERVICE_NAME=metastore
      - HIVE_CUSTOM_CONF_DIR=/hive_custom_conf
    volumes:
      - ./hive_metastore/conf/metastore-standalone-site.xml:/hive_custom_conf/metastore-site.xml
      - ./hive_metastore/lib/hadoop-common-3.4.0.jar:/opt/hive/lib/hadoop-common-3.4.0.jar
      - ./hive_metastore/lib/hadoop-aws-3.4.0.jar:/opt/hive/lib/hadoop-aws-3.4.0.jar
      - ./hive_metastore/lib/bundle-2.26.9.jar:/opt/hive/lib/bundle-2.26.9.jar
      - ./hive_metastore/lib/guava-33.2.1-jre.jar:/opt/hive/lib/guava-33.2.1-jre.jar
      - ./hive_metastore/lib/mysql-connector-j-8.4.0.jar:/opt/hive/lib/mysql-connector-j-8.4.0.jar
    networks:
      - trino
    depends_on:
      - minio

  minio:
    image: minio/minio
    hostname: minio
    container_name: minio
    restart: unless-stopped
    ports:
      - 59000:9000
      - 59001:9001
    volumes:
      - ~/data/trino/minio/data:/data
    env_file: ./minio/.env
    command:
      minio server $MINIO_VOLUMES $MINIO_OPTS
    networks:
      - trino

  trino:
    image: trinodb/trino
    hostname: trino
    container_name: trino
    restart: unless-stopped
    ports:
      - 58080:8080
    volumes:
      - ./trino/conf/config.properties:/etc/trino/config.properties
      - ./trino/conf/log.properties:/etc/trino/log.properties
      - ./trino/conf/node.properties:/etc/trino/node.properties
      - ./trino/catalog/minio.properties:/etc/trino/catalog/minio.properties
      - ~/data/trino/trino/log:/data/trino/var/log
      - ~/data/trino/trino/run:/data/trino/var/run
    networks:
      - trino
    depends_on:
      - hive-metastore
      - minio

networks:
  trino:
    driver: bridge

#      - ./hive_metastore_mysql/entrypoint-initdb.d:/docker-entrypoint-initdb.d
