services:
  devops:
    image: getmeili/meilisearch
    container_name: meilisearch
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ~/Data/meilisearch/data:/meili_data
      - ~/Data/meilisearch/log:/var/log/meilisearch
